### ISSUE TITLE
Proper types matching for shape_elem_type* and DPCTLSyclEventRef 

### ISSUE THREAD

**Issue by chudur-budur** [IntelPython/dpnp#1243]
I was trying to implement a `diag` function for `numba_dpex`. Please refer to this [PR](https://github.com/IntelPython/numba-dpex/pull/414).

The thing is that some internals of dpnp has been changed since, for example, I couldn't find a proper way to match type for `shape_elem_type` in [`dpnp_diag_c()`](https://github.com/IntelPython/dpnp/blob/0.11.0/dpnp/backend/kernels/dpnp_krnl_arraycreation.cpp#L130)

Previously, the function signature used to be like this:
```c
void dpnp_diag_c(
        void* v_in, 
        void* result1, 
        const int k, 
        size_t* shape, 
        size_t* res_shape, 
        const size_t ndim, 
        const size_t res_ndim)
```
But now, it is:
```c
DPCTLSyclEventRef dpnp_diag_c(DPCTLSyclQueueRef q_ref,
                              void* v_in,
                              void* result1,
                              const int k,
                              shape_elem_type* shape,
                              shape_elem_type* res_shape,
                              const size_t ndim,
                              const size_t res_ndim,
                              const DPCTLEventVectorRef dep_event_vec_ref)
```

In the previous `numba_dpex` implementation for `diag`, we could do this by setting the signature as:
```python
sig = signature(
        types.void,
        types.voidptr,
        types.voidptr,
        types.intp,
        types.voidptr,
        types.voidptr,
        types.intp,
        types.intp,
    )
```
How do I write a correct signature for `dpnp_diag_c()`?

**Comment by antonwolfy** [comment]
@chudur-budur, dpnp still provides the function signature without DPCTLSyclEventRef for [dpnp_diag_c](https://github.com/IntelPython/dpnp/blob/6171a71a14822181fb496410bd775101216d9300/dpnp/backend/include/dpnp_iface.hpp#L1156):
```
template <typename _DataType>
INP_DLLEXPORT void dpnp_diag_c(void* array,
                               void* result,
                               const int k,
                               shape_elem_type* shape,
                               shape_elem_type* res_shape,
                               const size_t ndim,
                               const size_t res_ndim);
```
while [shape_elem_type](https://github.com/IntelPython/dpnp/blob/6171a71a14822181fb496410bd775101216d9300/dpnp/backend/include/dpnp_iface.hpp#L56) is just redefining `ssize_t` type:
```
typedef ssize_t shape_elem_type;
```
I believe it should be possible to continue using the current signature in `numba_dpex`, like:
```
sig = signature(
    types.void,
    types.voidptr,
    types.voidptr,
    types.intp,
    types.voidptr,
    types.voidptr,
    types.intp,
    types.intp,
)
```
since `shape` and `res_shape` are integer pointers, like it was previously, and so `types.voidptr` can be used.
