### ISSUE TITLE
Cannot install latest dev version with 2024 compiler packages

### ISSUE THREAD

**Issue by Hardcode84** [IntelPython/dpnp#1627]
`conda create -n test-dpnp python=3.10 dpnp=0.13.1 "dpcpp_win-64>=2024" -c dppy/label/dev -c conda-forge -c intel`
Fails with conflicts on windows.

**Comment by antonwolfy** [comment]
I've checked manually and the issue looks gone now.

I assume the the problem was caused that dpctl was built with DPC++ 2024.0 and published on `dppy/label/dev` channel, but dpnp hadn't been yet. Btw, once the first dpnp package was built with DPC++ 2024.0 and published on `dppy/label/dev` also, the conflict was resolved.

Please let me know if the issue is still visible.

**Comment by Hardcode84** [comment]
Yes, looks like it's working now, thanks.
